FROM golang:1.7-alpine

COPY . /go/src/github.com/reachlin/dvd4sf
WORKDIR /go/src/github.com/reachlin/dvd4sf

RUN set -ex \
    && apk add --no-cache --virtual .build-deps \
    gcc libc-dev \
    && go get ./... \
    && go install --ldflags '-extldflags "-static"' \
    && apk del .build-deps

CMD ["/go/bin/dvd4sf"]